{
  "swagger": "2.0",
  "info": {
    "versio": "1.0.0",
    "title": "API - eCommercio",
    "description": "Documentação da API, projeto: eCommercio",
    "version": "1.0.0"
  },
  "host": "localhost:3000",
  "basePath": "",
  "schemes": [
    "http"
  ],
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "paths": {
    "/cliente": {
      "get": {
        "tags": [
          "Cliente"
        ],
        "summary": "Listagem de todos os clientes cadastrados",
        "description": "",
        "parameters": [],
        "responses": {
          "201": {
            "description": "Retorno de usuários bem sucessido."
          },
          "500": {
            "description": "Erro Interno do Servidor"
          }
        }
      },
      "post": {
        "tags": [
          "Cliente"
        ],
        "summary": "Insere um novo cliente, com base nos parâmetros repassados.",
        "description": "",
        "parameters": [],
        "responses": {
          "201": {
            "description": "Cliente inserido com sucesso."
          },
          "500": {
            "description": "Erro Interno do Servidor"
          }
        }
      }
    },
    "/cliente/{id}": {
      "delete": {
        "tags": [
          "Cliente"
        ],
        "summary": "Deleta o cliente, baseado no id repassado.",
        "description": "",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "204": {
            "description": "Cliente deletado com sucesso."
          },
          "500": {
            "description": "Erro Interno do Servidor"
          }
        }
      },
      "put": {
        "tags": [
          "Cliente"
        ],
        "summary": "Atualiza os dados de um cliente, com base nos parâmetros repassados.",
        "description": "",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "body",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "id": {
                  "example": "any"
                }
              }
            }
          }
        ],
        "responses": {
          "204": {
            "description": "Campos dos clientes atualizados com sucesso"
          },
          "500": {
            "description": "Erro Interno do Servidor"
          }
        }
      },
      "patch": {
        "tags": [
          "Cliente"
        ],
        "summary": "Atualiza um dado de um cliente, específico, com base nos parâmetros repassados.",
        "description": "",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "body",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "id": {
                  "example": "any"
                }
              }
            }
          }
        ],
        "responses": {
          "204": {
            "description": "Campo do cadastro do cliente alterado com sucesso."
          },
          "500": {
            "description": "Erro Interno do Servidor"
          }
        }
      }
    },
    "/estoque": {
      "get": {
        "tags": [
          "Estoque"
        ],
        "summary": "Listagem de todos os estoques/quantidades de produtos cadastrados",
        "description": "",
        "parameters": [],
        "responses": {
          "201": {
            "description": "Consulta realizada com sucesso."
          },
          "500": {
            "description": "Erro Interno do Servidor"
          }
        }
      },
      "post": {
        "tags": [
          "Estoque"
        ],
        "summary": "Insere uma quantidade em estoque de um produto, com base nos parâmetros repassados.",
        "description": "",
        "parameters": [],
        "responses": {
          "201": {
            "description": "Quantidade de estoque do produto inserida com sucesso"
          },
          "500": {
            "description": "Erro Interno do Servidor"
          }
        }
      }
    },
    "/estoque/{id}": {
      "delete": {
        "tags": [
          "Estoque"
        ],
        "summary": "Deleta o estoque do produto, baseado no id repassado.",       
        "description": "",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "204": {
            "description": "Quantidade em estoque do produto deletada com sucesso."
          },
          "500": {
            "description": "Erro Interno do Servidor"
          }
        }
      },
      "put": {
        "tags": [
          "Estoque"
        ],
        "summary": "Atualiza os dados de estoque de um produto, com base nos parâmetros repassados.",
        "description": "",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "body",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "id": {
                  "example": "any"
                }
              }
            }
          }
        ],
        "responses": {
          "204": {
            "description": "Quantidade, local e demais dados atualizados com sucesso."
          },
          "500": {
            "description": "Erro Interno do Servidor"
          }
        }
      },
      "patch": {
        "tags": [
          "Estoque"
        ],
        "summary": "Atualiza um dado de um produto, específico, com base nos parâmetros repassados.",        
        "description": "",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "body",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "id": {
                  "example": "any"
                }
              }
            }
          }
        ],
        "responses": {
          "204": {
            "description": "Dado alterado com sucesso."
          },
          "500": {
            "description": "Erro Interno do Servidor"
          }
        }
      }
    },
    "/fornecedor": {
      "get": {
        "tags": [
          "Fornecedor"
        ],
        "summary": "Consulta a lista de fornecedores já existentes.",        
        "description": "",
        "parameters": [],
        "responses": {
          "201": {
            "description": "Listagem retornada com sucesso."
          },
          "500": {
            "description": "Erro Interno do Servidor"
          }
        }
      },
      "post": {
        "tags": [
          "Fornecedor"
        ],
        "summary": "Insere um fornecedor, com base nos parâmetros repassados.", 
        "description": "",
        "parameters": [],
        "responses": {
          "201": {
            "description": "Fornecedor inserido com sucesso"
          },
          "500": {
            "description": "Erro Interno do Servidor"
          }
        }
      }
    },
    "/fornecedor/{id}": {
      "delete": {
        "tags": [
          "Fornecedor"
        ],
        "summary": "Deleta um fornecedor, com base no parâmetro repassado.", 
        "description": "",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "204": {
            "description": "Fornecedor deletado com sucesso."
          },
          "500": {
            "description": "Erro Interno do Servidor"
          }
        }
      },
      "put": {
        "tags": [
          "Fornecedor"
        ],
        "summary": "Atualiza um fornecedor, com base nos parâmetros repassados.", 
        "description": "",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "body",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "id": {
                  "example": "any"
                }
              }
            }
          }
        ],
        "responses": {
          "204": {
            "description": "Cadastro de fornecedores atualizado com sucesso."
          },
          "500": {
            "description": "Erro Interno do Servidor"
          }
        }
      },
      "patch": {
        "tags": [
          "Fornecedor"
        ],
        "summary": "Alterado um dado, em específico, do fornecedor, com base no parâmetro repassado.", 
        "description": "",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "body",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "id": {
                  "example": "any"
                }
              }
            }
          }
        ],
        "responses": {
          "204": {
            "description": "Conteúdo especificado alterado com sucesso."
          },
          "500": {
            "description": "Erro Interno do Servidor"
          }
        }
      }
    },
    "/produto": {
      "get": {
        "tags": [
          "Produto"
        ],
        "summary": "Listagem de todos os produtos cadastrados.", 
        "description": "",
        "parameters": [],
        "responses": {
          "201": {
            "description": "Consulta realizada com sucesso"
          },
          "500": {
            "description": "Erro Interno do Servidor"
          }
        }
      },
      "post": {
        "tags": [
          "Produto"
        ],
        "summary": "Insere um produto, com base nos parâmetros repassados",
        "description": "",
        "parameters": [],
        "responses": {
          "201": {
            "description": "Produto inserido com sucesso."
          },
          "500": {
            "description": "Erro Interno do Servidor"
          }
        }
      }
    },
    "/produto/{id}": {
      "delete": {
        "tags": [
          "Produto"
        ],
        "summary": "Deleta um produto, com base no id repassado.",
        "description": "",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "204": {
            "description": "Produto excluído com sucesso."
          },
          "500": {
            "description": "Erro Interno do Servidor"
          }
        }
      },
      "put": {
        "tags": [
          "Produto"
        ],
        "summary": "Atualiza os dados dos produtos, com base no parâmetro repassado",
        "description": "",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "body",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "id": {
                  "example": "any"
                }
              }
            }
          }
        ],
        "responses": {
          "204": {
            "description": "Produto atualizado com sucesso."
          },
          "500": {
            "description": "Erro Interno do Servidor"
          }
        }
      },
      "patch": {
        "tags": [
          "Produto"
        ],
        "summary": "Atualiza um dado em específico do produto, com base no parâmetro repassado.",
        "description": "",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "body",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "id": {
                  "example": "any"
                }
              }
            }
          }
        ],
        "responses": {
          "204": {
            "description": "Conteudo atualizado com sucesso."
          },
          "500": {
            "description": "Erro Interno do Servidor"
          }
        }
      }
    },
    "/venda": {
      "get": {
        "tags": [
          "Venda"
        ],
        "summary": "Listagem de todas as vendas cadastradas/realizadas.",
        "description": "",
        "parameters": [],
        "responses": {
          "201": {
            "description": "Consulta realizada com sucesso"
          },
          "500": {
            "description": "Erro Interno do Servidor"
          }
        }
      },
      "post": {
        "tags": [
          "Venda"
        ],
        "summary": "Insere uma nova venda, com base nos parametros repassados.",
        "description": "",
        "parameters": [],
        "responses": {
          "201": {
            "description": "Venda inserida com sucesso."
          },
          "500": {
            "description": "Erro Interno do Servidor"
          }
        }
      }
    },
    "/venda/{id}": {
      "delete": {
        "tags": [
          "Venda"
        ],
        "summary": "Deleta uma venda, com base no id repassado por parâmetro.",
        "description": "",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "204": {
            "description": "Venda deletada com sucesso"
          },
          "500": {
            "description": "Erro Interno do Servidor"
          }
        }
      },
      "put": {
        "tags": [
          "Venda"
        ],
        "summary": "Atualiza os dados da venda, com base nos parâmetros inseridos/atualizados.",
        "description": "",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "body",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "id": {
                  "example": "any"
                }
              }
            }
          }
        ],
        "responses": {
          "204": {
            "description": "Venda atualizada com sucesso."
          },
          "500": {
            "description": "Erro Interno do Servidor"
          }
        }
      },
      "patch": {
        "tags": [
          "Venda"
        ],
        "summary": "Atualiza um dado em específico da venda, com base nos parametros inseridos/repassados.",
        "description": "",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "body",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "id": {
                  "example": "any"
                }
              }
            }
          }
        ],
        "responses": {
          "204": {
            "description": "Venda atualizada"
          },
          "500": {
            "description": "Erro Interno do Servidor"
          }
        }
      }
    }
  }
}